### ISSUE TITLE
Un/Pinning a command message will execute that command

### ISSUE THREAD

**Issue by Milkenm** [ComputerMaster1st/Railgun#42]
![image](https://user-images.githubusercontent.com/26096762/76714983-1198d880-6722-11ea-8a37-2d43bee56dfc.png)

**Comment by ComputerMaster1st** [comment]
Hi There,

What's in the pinned message? It'll help me track down the problem faster.

**Comment by ComputerMaster1st** [comment]
Hi There,

Should be fixed with Commit 8fdf7f91.

**Comment by Milkenm** [comment]
Yah but I think you didn't refresh the bot yet since it's still broken

**Comment by ComputerMaster1st** [comment]
Hi There,

I've applied the fix now. Never knew I failed to upload for it. My mistake. Check to see if it ignores messages which do get pinned. It's hard to test if a message was unpinned though as the library we use doesn't save before & after message states.

**Comment by Milkenm** [comment]
Ok, pinned messages are fixed. The problem now are unpinned messages

**Comment by ComputerMaster1st** [comment]
Hi there,

The issue with pinned messages is problematic. In order to ignore (un)pinned messages, I'll have to store every pinned message. If a msg get's unpinned, I'll have to hit the database for that message.

This in turn will add more latency to command handling due to more calls to the database. The next problem is messages that are pinned before Railgun knows about it. I basically have to add a function to scan all channels for pinned messages.

The next best thing I can do is remove the code that's currently implemented for ignoring msgs that are pinned and create a command to configure railgun to ignore modified messages as that's what pinned messages are classed as.

The command implementation will be the easiest and I don't think it'll affect anyone. If the ignore edit flag is checked, I can simply have Railgun ignore it and not output anything. Does mean adding a database call, however it does mean the command handler will not need to execute at all so we at least save some CPU resources that way.

Would you like me to implement a command to allow ignoring of modified messages?

**Comment by Milkenm** [comment]
Yah it would be nice

I don't think anyone would have a problem with that, at least I wouldn't

**Comment by ComputerMaster1st** [comment]
Hi There,

I've just checked the code and turns out there is an old & new message variable. This means I won't need to make a command. I can just do the pin check there.

**Comment by ComputerMaster1st** [comment]
Hi There,

The fix should be live now. Please check.

**Comment by Milkenm** [comment]
Broken, both pinning and unpinning

**Comment by ComputerMaster1st** [comment]
Hi There,

Oke, I'll implement a command then since caching doesn't appear to work.

**Comment by ComputerMaster1st** [comment]
Hi There,

Try using the command `rgserver config ignoreoldmsgs` please?

**Comment by ComputerMaster1st** [comment]
Hi There,

I've now tested this myself and is working. Command is available in my previous message.

Closing issue as it's now solved with command. :)

**Comment by Milkenm** [comment]
It's nice m8, gj 👌
